name: 'Prepare environment'
description: 'Setup Node.js with pnpm & Module Installation'

inputs:
  install-modules:
    description: Install node_modules
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: PNPM Setup
      uses: pnpm/action-setup@v4

    - name: Node.js Setup
      uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version-file: '.node-version'
        check-latest: true
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: Get pnpm store directory
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-

    - name: Install modules
      if: ${{ inputs.install-modules == 'true' }}
      shell: bash
      run: pnpm i --frozen-lockfile
