name: Stable release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      has-new-release: ${{ steps.release.outputs.new_release_published }}
      tag-name: ${{ steps.release.outputs.new_release_git_tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Semantic release
        id: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/release-notes-generator
            @semantic-release/github
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.has-new-release == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/environment-prepare

      - name: Bundle
        run: pnpm bundle

      - name: Build Package Info
        run: pnpm pkg:prepare version=${{ needs.release.outputs.tag-name }}

      - name: Register
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}